export const SET_WORKING_UNITS = "SET_WORKING_UNITS";
export const SET_CASES = "SET_CASES";
export const SET_ALL_PERSONS_INFO = "SET_ALL_PERSONS_INFO";
export const SET_SELECTED_USER = "SET_SELECTED_USER";
export const SET_POPUP = "SET_POPUP";
